add_lunch_combo vu_d2usc-userdebug
add_lunch_combo vu_d801-userdebug
add_lunch_combo vu_d800-userdebug
add_lunch_combo vu_d802-userdebug
add_lunch_combo vu_deb-userdebug
add_lunch_combo vu_dlx-eng
add_lunch_combo vu_flo-userdebug
add_lunch_combo vu_hammerhead-userdebug
add_lunch_combo vu_ls970-userdebug
add_lunch_combo vu_jfltexx-eng
add_lunch_combo vu_mako-userdebug
add_lunch_combo vu_maguro-userdebug
add_lunch_combo vu_m7-userdebug

